### ISSUE TITLE
Criava uma classe OperationsService com as seguintes operações: transafer, deposit, withdrawal, blockCard

### ISSUE THREAD

**Issue by giselacostamindera** [vDalken/FunctionalProgrammingProject#3]
https://github.com/vDalken/FunctionalProgrammingProject/blob/9f5d3a103988a191b4e1f37d11fa045a2a0cb14c/src/Main.java#L108

**Comment by vDalken** [comment]
Criei a class e agora todos os detalhes das operações estão agora abstraídos da classe main
