### ISSUE TITLE
Usar camelCase para o nome da variavel: bankDataHandler

### ISSUE THREAD

**Issue by giselacostamindera** [vDalken/FunctionalProgrammingProject#4]
https://github.com/vDalken/FunctionalProgrammingProject/blob/9f5d3a103988a191b4e1f37d11fa045a2a0cb14c/src/Main.java#L17

**Comment by vDalken** [comment]
Então seria bankAccountsHandler? Eu ainda não entendi muito bem o porquê de colocar camel case em algumas constantes. Eu sei que tinhas explicado, mas podias explicar de novo por favor?

**Comment by giselacostamindera** [comment]
Concordo ctg
