### ISSUE TITLE
Could be an inner class of BankAccount eg. https://www.geeksforgeeks.org/builder-pattern-in-java/

### ISSUE THREAD

**Issue by giselacostamindera** [vDalken/FunctionalProgrammingProject#5]
https://github.com/vDalken/FunctionalProgrammingProject/blob/9f5d3a103988a191b4e1f37d11fa045a2a0cb14c/src/BankAccountBuilder.java#L3

**Comment by vDalken** [comment]
Eu coloquei o builder pattern como uma inner static class, e resolvi todos os problemas que vieram com a mudança
